# Persistent boot-time memory policy. The "!" suffix means these writes run
# only during the normal boot invocation of systemd-tmpfiles.
w! /sys/kernel/mm/transparent_hugepage/enabled - - - - madvise
w! /sys/kernel/mm/transparent_hugepage/defrag - - - - defer+madvise
w! /sys/kernel/mm/transparent_hugepage/shmem_enabled - - - - advise
w! /sys/kernel/mm/transparent_hugepage/khugepaged/defrag - - - - 0
w! /sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none - - - - 409
w! /sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_swap - - - - 64
w! /sys/kernel/mm/ksm/run - - - - 0
w! /sys/kernel/mm/lru_gen/enabled - - - - 7
w! /sys/kernel/mm/lru_gen/min_ttl_ms - - - - 0
