name: Build

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Free up space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - name: Configure zswap
        run: |
          echo Y | sudo tee /sys/module/zswap/parameters/enabled
          echo zstd | sudo tee /sys/module/zswap/parameters/compressor
          echo 40 | sudo tee /sys/module/zswap/parameters/max_pool_percent
          echo 1 | sudo tee /sys/module/zswap/parameters/shrinker_enabled

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16

      - name: Optimize VM parameters
        run: |
          sudo sysctl -w vm.page-cluster=0
          sudo sysctl -w vm.swappiness=180

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch tags
        if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        run: git fetch --tags --force

      - name: Get current tag
        if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        run: echo "current_tag=$(git describe --tags --abbrev=0 --exact-match 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Get previous tag
        if: ${{ env.current_tag != '' }}
        run: echo "previous_tag=$(git describe --tags --abbrev=0 ${{ env.current_tag }}^ 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: ${{ env.current_tag != '' && env.previous_tag != '' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build . -t charcoal

      - name: Build Kernel
        run: |
          docker run --rm \
            -v ${PWD}:/project \
            charcoal chown -R nobody /project

          docker run --rm \
            -e MAKEFLAGS="-j3" \
            -v ${PWD}:/project \
            charcoal sudo -u nobody makepkg -Ccf

      - name: Upload Artifacts
        if: ${{ env.current_tag == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-charcoal
          path: linux-charcoal-*.pkg.tar.zst
          if-no-files-found: warn

      - name: Publish release
        if: ${{ env.current_tag != '' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.current_tag }}
          name: ${{ env.current_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
          artifactContentType: application/zstd
          body: ${{ steps.changelog.outputs.changelog }}
          artifacts: linux-charcoal-*.pkg.tar.zst
